Repository antvis/XFlow, pull requests merged in 2022-07, with the labels that each got.

#294 fix: 修复 color 选择器全屏时被遮挡
  .changeset/swift-bottles-type.md
  packages/xflow-extension/src/flowchart-editor-panel/control-map-service/components/fields/color.tsx
  packages/xflow-extension/src/flowchart-node-panel/style/index.less
Labels: PR(fix), PR: unreviewed, size/M, pkg:xflow-extension

#296 fix build error
  .changeset/curly-needles-speak.md
  .gitignore
  .npmrc
Labels: bug, PR(fix), PR: unreviewed, size/S, pkg:xflow-extension

#298 chore: add npmrc. config
  .changeset/breezy-weeks-develop.md
  .changeset/curly-needles-speak.md
  .changeset/eight-timers-rush.md
  .changeset/fifty-eyes-rush.md
  .npmrc
Labels: PR(fix), PR: unreviewed, size/S
