Repository antvis/XFlow, pull requests merged in 2023-11, with the labels that each got.

#426 feat: add apps/basic dag page and control
  apps/basic/config/routes.ts
  apps/basic/package.json
  apps/basic/src/pages/dag/control/index.less
  apps/basic/src/pages/dag/control/index.tsx
  apps/basic/src/pages/dag/dnd/dnd.less
  apps/basic/src/pages/dag/dnd/dnd.tsx
  apps/basic/src/pages/dag/dnd/search/index.less
  apps/basic/src/pages/dag/dnd/search/index.tsx
  apps/basic/src/pages/dag/index.less
  apps/basic/src/pages/dag/index.tsx
  apps/basic/src/pages/dag/node.less
  apps/basic/src/pages/dag/shape.tsx
  packages/core/src/index.ts
Labels: size/XL, PR: unreviewed

#429 feat:config-components && add node status
  apps/basic/src/pages/dag/config-drawer/index.tsx
  apps/basic/src/pages/dag/execute-all/index.tsx
  apps/basic/src/pages/dag/index.tsx
Labels: PR: unreviewed, size/L

#427 feat: add diff graph
  apps/basic/config/config.ts
  apps/basic/config/routes.ts
  apps/basic/package.json
  apps/basic/src/pages/diff/index.tsx
  packages/diff/README.en-US.md
  packages/diff/README.md
  packages/diff/jest.config.js
  packages/diff/package.json
  packages/diff/project.json
  packages/diff/src/components/DiffGraph/index.tsx
  packages/diff/src/components/DiffGraph/tool.tsx
  packages/diff/src/components/index.ts
  packages/diff/src/index.ts
  packages/diff/src/styles/index.less
  packages/diff/src/types/index.ts
  packages/diff/src/util/index.ts
  packages/diff/tsconfig.json
  packages/diff/tsup.config.js
  pnpm-lock.yaml
Labels: PR(feature), size/XL, PR: unreviewed

#431 refactor:update dag
  apps/basic/src/pages/dag/config-drawer/index.tsx
  apps/basic/src/pages/dag/connect.tsx
  apps/basic/src/pages/dag/dnd/dnd.tsx
  apps/basic/src/pages/dag/execute-all/index.tsx
  apps/basic/src/pages/dag/index.tsx
  apps/basic/src/pages/dag/shape.tsx
  apps/basic/src/pages/dag/toolbar/index.tsx
Labels: PR: unreviewed, needs-more-info, size/L

#432 feat: add diff graph demo
  apps/basic/src/pages/diff/index.tsx
Labels: PR(feature), PR: unreviewed, size/L

#433 feat: add flowchart
  apps/basic/config/routes.ts
  apps/basic/package.json
  apps/basic/src/pages/dag/control/index.less
  apps/basic/src/pages/dag/control/index.tsx
  apps/basic/src/pages/dag/execute-all/index.tsx
  apps/basic/src/pages/dag/index.tsx
  apps/basic/src/pages/flow/connector.tsx
  apps/basic/src/pages/flow/dnd.tsx
  apps/basic/src/pages/flow/edge.tsx
  apps/basic/src/pages/flow/index.less
  apps/basic/src/pages/flow/index.tsx
  apps/basic/src/pages/flow/keyboard.tsx
  apps/basic/src/pages/flow/node.tsx
  packages/core/package.json
  packages/core/src/components/Control.tsx
  packages/core/src/components/index.ts
  packages/core/src/styles/index.less
  packages/diff/src/components/DiffGraph/tool.tsx
  packages/diff/src/util/index.ts
Labels: PR: unreviewed, size/XXL

#434 feat: add group demo
  apps/basic/config/routes.ts
  apps/basic/package.json
  apps/basic/src/pages/group/ContextMenu/index.less
  apps/basic/src/pages/group/ContextMenu/index.tsx
  apps/basic/src/pages/group/GroupNode/index.less
  apps/basic/src/pages/group/GroupNode/index.tsx
  apps/basic/src/pages/group/NormalNode/index.less
  apps/basic/src/pages/group/NormalNode/index.tsx
  apps/basic/src/pages/group/const.ts
  apps/basic/src/pages/group/dagreLayout.ts
  apps/basic/src/pages/group/index.less
  apps/basic/src/pages/group/index.tsx
  apps/basic/src/pages/group/tools.tsx
  apps/basic/src/pages/group/type.ts
  apps/basic/src/pages/group/utils.ts
  packages/core/src/types/index.ts
  pnpm-lock.yaml
Labels: PR: unreviewed, needs-more-info, size/XXL

#435 feat: add dag demo an update control
  apps/basic/src/pages/dag/execute-all/index.tsx
  apps/basic/src/pages/dag/index.tsx
  apps/basic/src/pages/dag/node.tsx
  apps/basic/src/pages/dag/toolbar/index.tsx
  apps/basic/src/pages/flow/dnd.tsx
  apps/basic/src/pages/flow/edge.tsx
  apps/basic/src/pages/flow/index.less
  apps/basic/src/pages/flow/index.tsx
  apps/basic/src/pages/flow/node.tsx
  packages/core/package.json
  packages/core/src/components/Control.tsx
  packages/core/src/styles/index.less
Labels: size/XL, PR: unreviewed

#436 feat: add node dropDown
  apps/basic/src/pages/dag/config-drawer/index.tsx
  apps/basic/src/pages/dag/node.less
  apps/basic/src/pages/dag/shape.tsx
  apps/basic/src/pages/dag/toolbar/index.tsx
Labels: PR: unreviewed, size/L

#441 fix(core): Cannot read properties of null (reading hasOwnProperty)
  packages/core/src/util/object.ts
Labels: PR(fix), PR: unreviewed, needs-more-info, size/XS

#440 feat: support react lowest version 16.8.6
  apps/basic/src/pages/group/GroupNode/index.tsx
  apps/basic/src/pages/group/NormalNode/index.tsx
  apps/basic/src/pages/group/index.tsx
  apps/basic/src/pages/group/tools.tsx
  packages/core/package.json
  packages/core/src/components/Background.tsx
  packages/core/src/components/Clipboard.tsx
  packages/core/src/components/Control.tsx
  packages/core/src/components/Graph.tsx
  packages/core/src/components/Grid.tsx
  packages/core/src/components/History.tsx
  packages/core/src/components/Minimap.tsx
  packages/core/src/components/Snapline.tsx
  packages/core/src/components/State.tsx
  packages/core/src/components/Transform.tsx
  packages/core/src/components/Wrapper.tsx
  packages/core/src/components/XFlow.tsx
  packages/core/src/context/GraphContext.tsx
  packages/core/src/context/StoreContext.tsx
  packages/diff/package.json
  packages/diff/src/components/DiffGraph/index.tsx
  packages/diff/src/components/DiffGraph/tool.tsx
  packages/diff/tsconfig.json
  pnpm-lock.yaml
  tooling/tsconfig/tsconfig.json
Labels: PR: unreviewed, needs-more-info, size/XXL
