Repository antvis/XFlow, pull requests merged in 2024-07, with the labels that each got.

#458 fix: 修复 <Grid/> 组件参数不生效问题
  packages/core/src/components/Grid.tsx
Labels: PR: unreviewed, needs-more-info, size/XS

#469 Update contributing.md to clarify installation of Nx and not Turborepo
  CONTRIBUTING.md
Labels: PR: unreviewed, size/XS

#471 chore: Update code examples apps/basic/src/pages/dag/toolbar/index.tsx function name
  apps/basic/src/pages/dag/toolbar/index.tsx
Labels: stale, PR: unreviewed, size/XS

#472 feat: add onPortRendered onEdgeLabelRendered createCellView graph options
  packages/core/src/components/Graph.tsx
  packages/core/src/types/index.ts
Labels: PR: unreviewed, needs-more-info, size/S
